### PR TITLE
add requirements.txt

### PR DESCRIPTION
**Pull request by andrew000**
add requirements.txt

### CODE REVIEW

**Comment by Poolitzer** [comment]
Hey, good idea, I always forget that. I think minimal versions would be good though. Want to add it? ptb would be 12.4. pymongo no idea.

**Comment by andrew000** [comment]
I want to refactor requirements.txt.

Wait for new commit

**Comment by andrew000** [comment]
So. It's stable, secure and paranoid requirements.txt

**Comment by Poolitzer** [comment]
Ahaha, I love it

**Comment by Poolitzer** [comment]
So I just tried installing via your requirements, and it didnt work out because of the hashes. Maybe dont do them. Lets just stick with it, plain and simple, as it is. pymongo, pythontelegrambot.

**Pull request closed without merging**
